version: '3.5'

services:
  redis:
    image: 'redis:latest'
    networks: ['agtranNetwork']
  db:
    image: 'postgres:12'
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'typeormtest'
    networks: ['agtranNetwork']
  app:
    image: 'antoniangga/agtran-testv2'
    restart: always
    build: .
    environment:
      - PORT=5000
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=typeormtest
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=typeormtest
      - REDIS_HOST=redis
    ports:
      - '5000:5000'
    networks: ['agtranNetwork']
    links:
      - db
      - redis
networks: { agtranNetwork: {} }
