version: '3.5'

services:
  redis:
    image: 'redis:latest'
  db:
    image: 'postgres:12'
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'typeormtest'
  app:
    image: 'antoniangga/agtran-testv2'
    restart: always
    build: .
    environment:
      - PORT=5000
      - POSTGRES_HOST='localhost'
      - POSTGRES_PORT=5432
      - POSTGRES_USER="typeormtest"
      - POSTGRES_PASSWORD="password"
      - POSTGRES_DB="typeormtest"
    ports:
      - '5000:5000'
    links:
      - db
      - redis
